mtl:
  mode: null
  port: null

data:
  path: dataset
  dataset: sim_warehouse
  with_noise: False #False,True

network:
  archit: split #split,mtan
  weight: equal #equal,dwa,uncert,autol
  task: all #primtasks
  grad_method: none #graddrop,pcgrad,cagrad
  autol_init: 0.1
  autol_lr: 0.0001
  
training:
  gpu: 0
  optim_lr: 0.1
  batch_size: 16
  optim: sgd #sgd,adam
  weight_decay: 0.0001
  early_stop: False
  scheduler: multisteplr #multisteplr, cosineannealing, steplr
  pretrained: False
  checkpoint_path: null
  epochs: 10

reprod:
  t_seed: True
  o_seed: 0

wandb:
  t_logger: True
  project_name: mtl-WarehouseSIM
  entity: wandbdimar

sweep: 
  sweep_t: True
  sweep_o: 'configs/sweep.yaml'