mtl:
  mode: null
  port: null

data:
  path: dataset
  dataset: sim_warehouse #nyuv2, taskonomy, sim_warehouse
  with_noise: False #False,True

network:
  archit: split #split,mtan
  weight: equal #equal,dwa,uncert,autol
  task: all #primtasks
  grad_method: cagrad #graddrop,pcgrad,cagrad,none
  autol_init: 1. #Changed from 0.1
  autol_lr: 0.0001
  
training:
  gpu: 0
  optim_lr: 0.16 # 0.16 # From sim_warehouse equal sweep
  batch_size: 8 # 8 # From sim_warehouse equal sweep
  optim: sgd #sgd,adam # From sim-warehouse equal sweep
  weight_decay: 0.0001
  early_stop: False
  scheduler: cosineannealing #multisteplr, cosineannealing, steplr
  pretrained: False
  checkpoint_path: null
  epochs: 200 #Changed from 200

reprod:
  t_seed: True
  o_seed: 0

wandb:
  t_logger: True
  project_name: mtl-WarehouseSIM
  entity: wandbdimar

sweep: 
  sweep_t: False
  sweep_o: 'configs/sweep.yaml'